name: Build and Release

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.22.2"

            - name: Build executable
              run: go build -o roblox-downgrader.exe .

            - name: Generate release notes
              run: echo $(git log --format=%B -n 1 ${{ github.sha }}) > release-notes.txt

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  files: roblox-downgrader.exe
                  make_latest: true
                  tag_name: v1.0
                  body_path: release-notes.txt
                  append_body: true

            - name: Upload release artifact
              uses: actions/upload-artifact@v4
              with:
                  name: roblox-downgrader
                  path: roblox-downgrader.exe
