name: Build and Release

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.22.2"

            - name: Build executable
              run: go build -o roblox-downgrader.exe .

            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: roblox-downgrader.exe

            - name: Upload release artifact
              uses: actions/upload-artifact@v4
              with:
                  name: roblox-downgrader.exe
                  path: roblox-downgrader.exe
