name: Build and Release

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: "1.22.2"

            - name: Build executable
              run: go build -o roblox-downgrader.exe .

            - name: Create release
              id: create_release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  body: |
                      $(git log --format=%B --reverse)
                  draft: false
                  prerelease: false

            - name: Upload release artifact
              uses: actions/upload-artifact@v4
              with:
                  name: roblox-downgrader.exe
                  path: roblox-downgrader.exe
